class Boss:
    moss_mother = "Moss Mother"
    double_moss_mother = "Double Moss Mother"
    bell_beast = "Bell Beast"
    lace = "Lace"
    fourth_chorus = "Fourth Chorus"
    moorwing = "Moorwing"
    sister_splinter = "Sister Splinter"
    widow = "Widow"
    great_conchflies = "Great Conchflies"
    last_judge = "Last Judge"
    cogwork_dancers = "Cogwork Dancers"
    trobbio = "Trobbio"
    tormented_trobbio = "Tormented Trobbio"
    groal_the_great = "Groal the Great"
    the_unraveled = "The Unraveled"
    disgraced_chef_lugoli = "Disgraced Chef Lugoli"
    craggler = "Craggler"
    father_of_the_flame = "Father of the Flame"
    voltvyrm = "Voltvyrm"
    second_sentinel = "Second Sentinel"
    broodmother = "Broodmother"
    plasmified_zango = "Plasmified Zango"
    shrine_guardian_seth = "Shrine Guardian Seth"
    palestag = "Palestag"
    lost_garmond = "Lost Garmond"
    pinstress = "Pinstress"
    gurr_the_outcast = "Gurr the Outcast"
    watcher_at_the_edge = "Watcher at the Edge"
    crawfather = "Crawfather"
    # summoned_savior = "Summoned Savior"
    shakra = "Shakra"
    garmond_and_zaza = "Garmond and Zaza"

    savage_beastfly_beast = "Savage Beastfly (Beast)"
    savage_beastfly_wish = "Savage Beastfly (Wish)"

    skull_tyrant_wish = "Skull Tyrant (Wish)"
    skull_tyrant_bone_bottom = "Skull Tyrant (Bone Bottom)"

    phantom = "Phantom"

    raging_conchfly = "Raging Conchfly"
    first_sinner = "First Sinner"
    lace_cradle = "Lace (Cradle)"
    grand_mother_silk = "Grand Mother Silk"

    bell_eater = "Bell Eater"
    black_thread_moss_mother = "Black Thread Moss Mother"
    crust_king_khann = "Crust King Khann"
    nyleth = "Nyleth"
    skarrsinger_karmelita = "Skarrsinger Karmelita"
    clover_dancers = "Clover Dancers"
    lost_lace = "Lost Lace"
