all_region_names = []


def region(name: str) -> str:
    all_region_names.append(name)
    return name


class RegionName:
    menu = region("Menu")
    moss_grotto = region("Moss Grotto")
    bone_bottom = region("Bone Bottom")

    marrow_west = region("The Marrow - West")
    marrow_bellway = region("The Marrow - Bellway Station")
    marrow_east = region("The Marrow - East")
    marrow_bellway_north_alcove = region("The Marrow - North Alcove")

    deep_docks_entrance = region("Deep Docks - Entrance")
    deep_docks_swift_step = region("Deep Docks - Swift Step")
    deep_docks_forge_daughter = region("Deep Docks - Forge Daughter")
    deep_docks_lace = region("Deep Docks - Lace")
    deep_docks_bell = region("Deep Docks - Bell")
    deep_docks_diving_bell = region("Deep Docks - Diving Bell")

    far_fields_entrance = region("Far Fields - Entrance")
    far_fields_pilgrims_rest = region("Far Fields - Pilgrim's Rest")
    far_fields_seamstress = region("Far Fields - Seamstress")
    far_fields_east = region("Far Fields - East")
    far_fields_fourth_chorus = region("Far Fields - Fourth Chorus")
    far_fields_beastfly = region("Far Fields - BeastFly")
    far_fields_climb = region("Far Fields - Climb")
    far_fields_fields = region("Far Fields - Fields")

    hunters_march = region("Hunter's March")
    chapel_of_beast = region("Chapel of the Beast")

    greymoor_above_far_fields = region("Greymoor - Above Far Fields")
    greymoor_craw_lake = region("Greymoor - Craw Lake")
    greymoor_spires = region("Greymoor - Spires")
    greymoor_bellway = region("Greymoor - Bellway")

    halfway_home = region("Halfway Home")
    halfway_home_alcove = region("Halfway Home - Alcove")

    wisp_thicket = region("Wisp Thicket")
    bellhart = region("Bellhart")
    shellwood = region("Shellwood")
    bellhart_upper = region("Upper Bellhart")
    bellhart_saved = region("Saved Bellhart")
    blasted_steps = region("Blasted Steps")
    blasted_steps_pinstress = region("Blasted Steps - Pinstress")
    blasted_steps_grand_gate = region("Blasted Steps Grand Gate")
    weavenest_atla = region("Weavenest Atla")

    craggler_cavern = region("Craggler Cavern")
    wormways_entrance = region("Wormways - Entrance")
    wormways_bottom_left = region("Wormways - Bottom Left")
    weavenest_karn = region("Weavenest Karn")

    sands_of_karak = region("Sands Of Karak")
    the_slab = region("The Slab")
    the_slab_shortcut_cave = region("The Slab - Shortcut Cave")
    mount_fay = region("Mount Fay")
    sinners_road = region("Sinner's Road")
    bilewater = region("Bilewater")
    bilewater_bellway = region("Bilewater - Bellway")
    bilewater_upper = region("Upper Bilewater")
    mist = region("The Mist")
    exhaust_organ = region("Exhaust Organ")
    putrified_ducts = region("Putrified Ducts")
    fleatopia = region("Fleatopia")
    cradle = region("The Cradle")
    cradle_with_soul_snare = region("The Cradle - Soul Snare")
    citadel = region("Citadel")
    underworks = region("Underworks")
    underworks_confessional = region("Underworks - Confessional")
    grand_gate = region("Grand Gate")
    choral_chambers = region("Choral Chambers")
    choral_chambers_above_bellway = region("Choral Chambers - Above Bellway")
    choral_chambers_bellway = region("Choral Chambers - Bellway")
    choral_chambers_outside = region("Choral Chambers - Outside")
    whiteward = region("Whiteward")
    whispering_vaults = region("Whispering Vaults")
    whispering_vaults_east = region("Whispering Vaults - East")
    memorium = region("Memorium")
    cogwork_core = region("Cogwork Core")
    high_halls = region("High Halls")
    verdania = region("Verdania")
    abyss = region("The Abyss")

    cradle_act_3 = region("The Cradle (Act 3)")
    escaped_cradle_act_3 = region("Escaped Cradle (Act 3)")
    wormways_plasmium = region("Plasmified Wormways")
    choral_chambers_act_3 = region("Choral Chambers (Act 3)")
    blasted_steps_act_3 = region("Blasted Steps (Act 3)")
    mount_fay_act_3 = region("Mount Fay (Act 3)")
