all_region_names = []


def region(name: str) -> str:
    all_region_names.append(name)
    return name


class RegionName:
    menu = region("Menu")
    moss_grotto = region("Moss Grotto")
    bone_bottom = region("Bone Bottom")
    bone_bottom_wishwall = region("Bone Bottom Wishwall")

    bonegrave = region("Bonegrave")
    chapel_of_the_wanderer = region("Chapel of the Wanderer")

    marrow_west = region("The Marrow - West")
    marrow_bellway = region("The Marrow - Bellway Station")
    marrow_east = region("The Marrow - East")
    marrow_bellway_north_alcove = region("The Marrow - North Alcove")

    marrow_east_bone_bottom_wishes = region("The Marrow - East Started Bone Bottom Wishes")
    marrow_east_flintbeetles = region("The Marrow - East - Volatile FlintBeetles")
    marrow_east_skull_tyrant = region("The Marrow - East - Skull Tyrant")
    bone_bottom_after_skull_tyrant = region("Bone Bottom - Skull Tyrant Defeated Once")

    deep_docks_entrance = region("Deep Docks - Entrance")
    deep_docks_swift_step = region("Deep Docks - Swift Step")
    deep_docks_forge_daughter = region("Deep Docks - Forge Daughter")
    deep_docks_lace = region("Deep Docks - Lace")
    deep_docks_bell = region("Deep Docks - Bell")
    deep_docks_diving_bell = region("Deep Docks - Diving Bell")

    far_fields_entrance = region("Far Fields - Entrance")
    far_fields_pilgrims_rest = region("Far Fields - Pilgrim's Rest")
    far_fields_seamstress = region("Far Fields - Seamstress")
    far_fields_east = region("Far Fields - East")
    far_fields_fourth_chorus = region("Far Fields - Fourth Chorus")
    far_fields_beastfly = region("Far Fields - BeastFly")
    far_fields_climb = region("Far Fields - Climb")
    far_fields_fields = region("Far Fields - Fields")

    hunters_march = region("Hunter's March")
    chapel_of_the_beast = region("Chapel of the Beast")

    greymoor_above_far_fields = region("Greymoor - Above Far Fields")
    greymoor_craw_lake = region("Greymoor - Craw Lake")
    greymoor_spires = region("Greymoor - Spires")
    greymoor_bellway = region("Greymoor - Bellway")
    chapel_of_the_reaper = region("Chapel of the Reaper")
    yarnaby = region("Greymoor - Yarnaby's Home")
    yarnaby_with_steel_spines = region("Greymoor - Yarnaby's Home with Steel Spines")

    halfway_home = region("Halfway Home")
    halfway_home_alcove = region("Halfway Home - Alcove")

    wisp_thicket = region("Wisp Thicket")

    bellhart = region("Bellhart")
    shellwood = region("Shellwood")
    bellhart_upper = region("Upper Bellhart")
    bellhart_saved = region("Saved Bellhart")
    pinmaster_home = region("Bellhart - Pinmaster Home")

    greyroot = region("Shellwood - GreyRoot")
    greyroot_rite_of_pollip = region("Shellwood - GreyRoot Rite Of The Pollip")
    greyroot_with_twisted_bud = region("Shellwood - GreyRoot With Twisted Bud")

    bellhart_wishwall = region("Bellhart Wishwall")
    bellhart_wishwall_after_tipp = region("Bellhart Wishwall - Tipp saved")
    bellhart_wishwall_bellhart_restored = region("Bellhart Wishwall - Bellhart Restored")
    bellhart_wishwall_after_beastfy = region("Bellhart Wishwall - Defeated Beastfly")
    bellhart_wishwall_all_maps_faydown_and_two_melodies = region("Bellhart Wishwall - All Maps, Faydown Cloak and Two Melodies")
    bellhart_wishwall_after_needle = region("Bellhart Wishwall - One Needle Upgrade")
    bellhart_wishwall_after_needle_and_relic = region("Bellhart Wishwall - One Needle Upgrade and One Relic")
    bellhart_wishwall_act_3 = region("Bellhart Wishwall - Act 3")
    bellhart_wishwall_with_strike = region("Bellhart Wishwall - With Needle Strike")
    bellhart_wishwall_after_awaiting_end = region("Bellhart Wishwall - Awaiting the End")
    bellhart_wishwall_with_silk_soar = region("Bellhart Wishwall - With Silk Soar")
    bellhart_wishwall_after_karmelita = region("Bellhart Wishwall - Met Karmelita")

    wish_shellwood_missing_courrier = region("Bellhart Wish - My Missing Courier")
    wish_sinners_road_missing_brother = region("Bellhart Wish - My Missing Brother")
    wish_pinmaster_oil = region("Bellhart Wish - Pinmaster's Oil")
    bellhart_delivery_wishes = region("Bellhart - Delivery Wishes")
    trail_end = region("Bellhart Wish - The Hidden Hunter")
    wish_heros_call = region("Bellhart Wish - Hero's Call")
    wish_dark_hearts = region("Bellhart Wish - Dark Hearts")
    wish_hidden_hunter = region("Bellhart Wish - The Hidden Hunter")

    blasted_steps = region("Blasted Steps")
    blasted_steps_pinstress = region("Blasted Steps - Pinstress")
    blasted_steps_grand_gate = region("Blasted Steps Grand Gate")
    weavenest_atla = region("Weavenest Atla")

    craggler_cavern = region("Craggler Cavern")
    wormways_entrance = region("Wormways - Entrance")
    wormways_bottom_left = region("Wormways - Bottom Left")
    weavenest_karn = region("Weavenest Karn")

    sands_of_karak = region("Sands Of Karak")

    the_slab = region("The Slab")
    the_slab_shortcut_cave = region("The Slab - Shortcut Cave")
    the_slab_first_sinner_cave = region("The Slab - First Sinner Cave")

    mount_fay = region("Mount Fay")
    sinners_road = region("Sinner's Road")
    sinners_road_chef_lugoli = region("Sinner's Road - Lugoli's Kitchen")

    bilewater = region("Bilewater")
    bilewater_bellway = region("Bilewater - Bellway")
    bilewater_upper = region("Upper Bilewater")
    mist = region("The Mist")
    exhaust_organ = region("Exhaust Organ")
    putrified_ducts = region("Putrified Ducts")
    fleatopia = region("Fleatopia")
    cradle = region("The Cradle")
    cradle_with_soul_snare = region("The Cradle - Soul Snare")
    citadel = region("Citadel")

    underworks_act_2 = region("Underworks - Act 2")
    underworks = region("Underworks")
    underworks_confessional = region("Underworks - Confessional")
    underworks_cauldron = region("Underworks - The Cauldron")
    twelfth_architect = region("Underworks - Twelfth Architect")
    chapel_of_the_architect = region("Chapel of the Architect")

    grand_gate = region("Grand Gate")
    choral_chambers = region("Choral Chambers")
    choral_chambers_above_bellway = region("Choral Chambers - Above Bellway")
    choral_chambers_bellway = region("Choral Chambers - Bellway")
    choral_chambers_outside = region("Choral Chambers - Outside")
    songclave = region("Choral Chambers - Songclave")

    whiteward = region("Whiteward")
    whispering_vaults = region("Whispering Vaults")
    whispering_vaults_east = region("Whispering Vaults - East")
    memorium = region("Memorium")
    cogwork_core = region("Cogwork Core")
    high_halls = region("High Halls")
    verdania = region("Verdania")
    abyss = region("The Abyss")
    weavenest_absolom = region("Weavenest Absolom")

    cradle_act_3 = region("The Cradle (Act 3)")
    escaped_cradle_act_3 = region("Escaped Cradle (Act 3)")
    wormways_plasmium = region("Plasmified Wormways")
    choral_chambers_act_3 = region("Choral Chambers (Act 3)")
    blasted_steps_act_3 = region("Blasted Steps (Act 3)")
    mount_fay_act_3 = region("Mount Fay (Act 3)")
    moss_grotto_act_3 = region("Moss Grotto (Act 3)")
    ruined_chapel = region("Ruined Chapel")
    craw_lake_act_3 = region("Greymoor - Craw Lake (Act 3)")
    court_of_craws = region("Court of Craws")

    eva_0 = region("Meet Eva")
    eva_1 = region("Eva - 1 Crest Slot")
    eva_2 = region("Eva - 2 Crest Slot")
    eva_3 = region("Eva - 3 Crest Slot")
    eva_4 = region("Eva - 4 Crest Slot")
    eva_5 = region("Eva - 5 Crest Slot")
    eva_6 = region("Eva - 6 Crest Slot")
    eva_7 = region("Eva - 7 Crest Slot")
    eva_8 = region("Eva - 8 Crest Slot")
    eva_9 = region("Eva - 9 Crest Slot")
    eva_10 = region("Eva - 10 Crest Slot")
    eva_11 = region("Eva - 11 Crest Slot")
    eva_12 = region("Eva - 12 Crest Slot")
    eva_13 = region("Eva - 13 Crest Slot")
    eva_14 = region("Eva - 14 Crest Slot")
    eva_15 = region("Eva - 15 Crest Slot")
    eva_16 = region("Eva - 16 Crest Slot")
    eva_17 = region("Eva - 17 Crest Slot")
    eva_18 = region("Eva - 18 Crest Slot")
    eva_19 = region("Eva - 19 Crest Slot")
    eva_20 = region("Eva - 20 Crest Slot")
    eva_21 = region("Eva - 21 Crest Slot")
    eva_22 = region("Eva - 22 Crest Slot")
    eva_23 = region("Eva - 23 Crest Slot")
    eva_24 = region("Eva - 24 Crest Slot")
    eva_25 = region("Eva - 25 Crest Slot")
    eva_26 = region("Eva - 26 Crest Slot")
    eva_27 = region("Eva - 27 Crest Slot")
    eva_28 = region("Eva - 28 Crest Slot")
    eva_29 = region("Eva - 29 Crest Slot")
    eva_30 = region("Eva - 30 Crest Slot")
    eva_31 = region("Eva - 31 Crest Slot")
    eva_32 = region("Eva - 32 Crest Slot")
    eva_33 = region("Eva - 33 Crest Slot")
    eva_34 = region("Eva - 34 Crest Slot")
    eva_35 = region("Eva - 35 Crest Slot")
    eva_36 = region("Eva - 36 Crest Slot")
    eva_37 = region("Eva - 37 Crest Slot")
    eva_38 = region("Eva - 38 Crest Slot")
    eva_39 = region("Eva - 39 Crest Slot")
    eva_40 = region("Eva - 40 Crest Slot")
