from worlds.hk_silksong.strings.boss_names import Boss

all_region_names = []


def arena_region(boss_name: str) -> str:
    region_name = f"{boss_name} Arena"
    return region(region_name)


def defeated_region(boss_name: str) -> str:
    region_name = f"{boss_name} After Defeated"
    return region(region_name)


def region(name: str) -> str:
    all_region_names.append(name)
    return name


class RegionName:
    menu = region("Menu")
    bellway_travel = region("Bellway Travel")
    ventrica_travel = region("Ventrica Travel")
    use_silk_spear = region("Use SilkSpear")

    moss_grotto = region("Moss Grotto")
    bone_bottom = region("Bone Bottom")
    bone_bottom_wishwall = region("Bone Bottom Wishwall")
    bone_bottom_bellway = region("Bone Bottom - Bellway")

    bonegrave = region("Bonegrave")
    chapel_of_the_wanderer = region("Chapel of the Wanderer")

    marrow_west = region("The Marrow - West")
    mosshome = region("The Marrow - Mosshome")
    marrow_bellway = region("The Marrow - Bellway Station")
    marrow_bellway_north = region("The Marrow - North After Bellway")
    marrow_east = region("The Marrow - East")
    marrow_bellway_north_alcove = region("The Marrow - North Alcove")
    flea_caravan_marrow = region("The Marrow - Flea Caravan")
    lost_flea_wish = region("The Marrow - Lost Flea Wish")
    flea_caravan_marrow_with_5_fleas = region("The Marrow - Flea Caravan With 5 Fleas")

    marrow_east_bone_bottom_wishes = region("The Marrow - East Started Bone Bottom Wishes")
    marrow_east_flintbeetles = region("The Marrow - East - Volatile FlintBeetles")
    marrow_east_skull_tyrant = region("The Marrow - East - Skull Tyrant")
    bone_bottom_after_skull_tyrant = region("Bone Bottom - Skull Tyrant Defeated Once")

    deep_docks_entrance = region("Deep Docks - Entrance")
    deep_docks_bellway = region("Deep Docks - Bellway")
    deep_docks_bellway_flea_room = region("Deep Docks - Bellway Flea Room")
    deep_docks_swift_step = region("Deep Docks - Swift Step")
    deep_docks_swift_step_upper = region("Deep Docks - Above Swift Step")
    deep_docks_forge_daughter = region("Deep Docks - Forge Daughter")
    deep_docks_lace = region("Deep Docks - Lace")
    deep_docks_bell = region("Deep Docks - Bell")
    deep_docks_diving_bell = region("Deep Docks - Diving Bell")

    far_fields_entrance = region("Far Fields - Entrance")
    far_fields_bellway = region("Far Fields - Bellway")
    far_fields_pilgrims_rest = region("Far Fields - Pilgrim's Rest")
    far_fields_pilgrims_rest_rhinogrund = region("Far Fields - Rhinogrund Cave Behind Pilgrim's Rest")
    far_fields_seamstress = region("Far Fields - Seamstress")
    far_fields_east = region("Far Fields - East")
    far_fields_fourth_chorus = region("Far Fields - Fourth Chorus")
    far_fields_beastfly = region("Far Fields - BeastFly")
    far_fields_climb = region("Far Fields - Climb")
    far_fields_fields = region("Far Fields - Fields")

    hunters_march = region("Hunter's March")
    chapel_of_the_beast = region("Chapel of the Beast")

    greymoor_above_far_fields = region("Greymoor - Above Far Fields")
    greymoor_craw_lake = region("Greymoor - Craw Lake")
    greymoor_spires = region("Greymoor - Spires")
    greymoor_spires_above_halfway_home = region("Greymoor - Spires Above Halfway Home")
    greymoor_spires_upper = region("Greymoor - Above Spires")
    greymoor_bellway = region("Greymoor - Bellway")
    chapel_of_the_reaper = region("Chapel of the Reaper")
    yarnaby = region("Greymoor - Yarnaby's Home")
    yarnaby_with_steel_spines = region("Greymoor - Yarnaby's Home with Steel Spines")

    halfway_home = region("Halfway Home")
    halfway_home_alcove = region("Halfway Home - Alcove")
    halfway_home_basement = region("Halfway Home - Basement")

    wisp_thicket = region("Wisp Thicket")
    underworks_from_wisp_thicket = region("Underworks - From Wisp Thicket")

    bellhart = region("Bellhart")
    shellwood = region("Shellwood")
    shellwood_entrance = region("Shellwood - Entrance")
    bellhart_upper = region("Upper Bellhart")
    bellhart_saved = region("Saved Bellhart")
    pinmaster_home = region("Bellhart - Pinmaster Home")
    bellhart_bellway = region("Bellhart - Bellway")
    bellhart_lower = region("Lower Bellhart")
    pinmaster_home_1_pale_oil = region("Bellhart - Pinmaster Home With 1 Pale Oil")
    pinmaster_home_2_pale_oils = region("Bellhart - Pinmaster Home With 2 Pale Oils")
    pinmaster_home_3_pale_oils = region("Bellhart - Pinmaster Home With 3 Pale Oils")

    greyroot = region("Shellwood - GreyRoot")
    greyroot_rite_of_pollip = region("Shellwood - GreyRoot Rite Of The Pollip")
    greyroot_with_twisted_bud = region("Shellwood - GreyRoot With Twisted Bud")
    shellwood_bellway = region("Shellwood - Bellway")

    bellhart_wishwall = region("Bellhart Wishwall")
    bellhart_wishwall_after_tipp = region("Bellhart Wishwall - Tipp saved")
    bellhart_wishwall_bellhart_restored = region("Bellhart Wishwall - Bellhart Restored")
    bellhart_wishwall_after_beastfy = region("Bellhart Wishwall - Defeated Beastfly")
    bellhart_wishwall_all_maps_faydown_and_two_melodies = region("Bellhart Wishwall - All Maps, Faydown Cloak and Two Melodies")
    bellhart_wishwall_after_needle = region("Bellhart Wishwall - One Needle Upgrade")
    bellhart_wishwall_after_needle_and_relic = region("Bellhart Wishwall - One Needle Upgrade and One Relic")
    bellhart_wishwall_act_3 = region("Bellhart Wishwall - Act 3")
    bellhart_wishwall_with_strike = region("Bellhart Wishwall - With Needle Strike")
    bellhart_wishwall_after_awaiting_end = region("Bellhart Wishwall - Awaiting the End")
    bellhart_wishwall_with_silk_soar = region("Bellhart Wishwall - With Silk Soar")
    bellhart_wishwall_after_karmelita = region("Bellhart Wishwall - Met Karmelita")

    wish_shellwood_missing_courrier = region("Bellhart Wish - My Missing Courier")
    wish_sinners_road_missing_brother = region("Bellhart Wish - My Missing Brother")
    wish_pinmaster_oil = region("Bellhart Wish - Pinmaster's Oil")
    bellhart_delivery_wishes = region("Bellhart - Delivery Wishes")
    trail_end = region("Bellhart Wish - The Hidden Hunter")
    wish_heros_call = region("Bellhart Wish - Hero's Call")
    wish_dark_hearts = region("Bellhart Wish - Dark Hearts")
    wish_hidden_hunter = region("Bellhart Wish - The Hidden Hunter")

    blasted_steps = region("Blasted Steps")
    blasted_steps_pinstress = region("Blasted Steps - Pinstress")
    blasted_steps_grand_gate = region("Blasted Steps Grand Gate")
    blasted_steps_shaft = region("Blasted Steps - Vertical Shaft")
    blasted_steps_bellway = region("Blasted Steps - Bellway")
    blasted_steps_grindle = region("Blasted Steps - Grindle Hiding Spot")
    blasted_steps_dice_pilgrim = region("Blasted Steps - Dice Pilgrim Cave")

    weavenest_atla = region("Weavenest Atla")
    weavenest_atla_moss_mothers = region("Weavenest Atla - Moss Mothers")

    craggler_cavern = region("Craggler Cavern")
    wormways_entrance = region("Wormways - Entrance")
    wormways_bottom_left = region("Wormways - Bottom Left")
    wormways_upper = region("Wormways - Upper")
    weavenest_karn = region("Weavenest Karn")

    sands_of_karak = region("Sands Of Karak")
    sands_of_karak_shaft = region("Sands Of Karak - Vertical Shaft")
    sands_of_karak_lower_right = region("Sands Of Karak - Lower Right")
    sands_of_karak_upper_right = region("Sands Of Karak - Upper Right")
    sands_of_karak_crustnut_room = region("Sands Of Karak - Crustnut Room")
    sands_of_karak_voltnest = region("Sands Of Karak - Voltnest")
    sands_of_karak_upper_left = region("Sands Of Karak - Upper Left")
    sands_of_karak_coral_tower = region("Sands Of Karak - Coral Tower")
    sands_of_karak_coral_tower_dream = region("Sands Of Karak - Coral Tower Dream")

    the_slab = region("The Slab")
    the_slab_bellway = region("The Slab - Bellway")
    the_slab_above_bench = region("The Slab - Above Bench")
    the_slab_indolent = region("The Slab - With Indolent Key")
    the_slab_shortcut_cave = region("The Slab - Shortcut Cave")
    the_slab_first_sinner_cave = region("The Slab - First Sinner Cave")

    mount_fay = region("Mount Fay")
    mount_fay_ceiling_cave = region("Mount Fay - Ceiling Cave")

    sinners_road = region("Sinner's Road")
    sinners_road_chef_lugoli = region("Sinner's Road - Lugoli's Kitchen")
    sinners_road_after_chef_lugoli = region("Sinner's Road - After Chef Lugoli")

    bilewater = region("Bilewater")
    bilewater_bellway = region("Bilewater - Bellway")
    bilewater_upper = region("Upper Bilewater")
    mist = region("The Mist")
    exhaust_organ = region("Exhaust Organ")
    putrified_ducts = region("Putrified Ducts")
    putrified_ducts_bellway = region("Putrified Ducts - Bellway")
    putrified_ducts_vog_passage = region("Putrified Ducts - Vog's Camp")
    fleatopia = region("Fleatopia")
    festival_of_the_flea = region("Fleatopia - Festival of the Flea")
    cradle = region("The Cradle")
    terminus_ventrica = region("Terminus - Ventrica")
    cradle_with_soul_snare = region("The Cradle - Soul Snare")
    citadel = region("Citadel")

    underworks_act_2 = region("Underworks - Act 2")
    underworks = region("Underworks")
    underworks_ventrica = region("Underworks - Ventrica")
    underworks_confessional = region("Underworks - Confessional")
    underworks_cauldron = region("Underworks - The Cauldron")
    twelfth_architect = region("Underworks - Twelfth Architect")
    chapel_of_the_architect = region("Chapel of the Architect")

    grand_gate = region("Grand Gate")
    choral_chambers = region("Choral Chambers")
    choral_chambers_ventrica = region("Choral Chambers - Ventrica")
    choral_chambers_above_bellway = region("Choral Chambers - Above Bellway")
    choral_chambers_bellway = region("Choral Chambers - Grand Bellway")
    grand_bellway_ventrica = region("Grand Bellway - Ventrica")
    choral_chambers_great_gourmand = region("Choral Chambers - Great Gourmand Room")
    choral_chambers_great_gourmand_with_5_delicacies = region("Choral Chambers - Great Gourmand Room with 5 Delicacies")
    choral_chambers_outside = region("Choral Chambers - Outside")
    choral_chambers_outside_alcove = region("Choral Chambers - Outside Alcove")
    choral_chambers_vent = region("Choral Chambers - Vent")
    songclave = region("Choral Chambers - Songclave")
    choral_chambers_pale_oil_room = region("Choral Chambers - Pale Oil Room")
    first_shrine_ventrica = region("First Shrine - Ventrica")

    whiteward = region("Whiteward")
    whiteward_ceiling = region("Whiteward - Ceiling")
    whispering_vaults = region("Whispering Vaults")
    whispering_vaults_east = region("Whispering Vaults - East")
    memorium = region("Memorium")
    memorium_ventrica = region("Memorium - Ventrica")
    memorium_giant_flea = region("Memorium - Giant Flea")
    memorium_outside = region("Memorium - Outside")
    cogwork_core = region("Cogwork Core")
    high_halls = region("High Halls")
    high_halls_ventrica = region("High Halls - Ventrica")
    verdania = region("Verdania")
    abyss = region("The Abyss")
    weavenest_absolom = region("Weavenest Absolom")
    abyss_with_everbloom = region("The Abyss With Everbloom")

    cradle_act_3 = region("The Cradle (Act 3)")
    escaped_cradle_act_3 = region("Escaped Cradle (Act 3)")
    wormways_plasmium = region("Plasmified Wormways")
    choral_chambers_act_3 = region("Choral Chambers (Act 3)")
    blasted_steps_act_3 = region("Blasted Steps (Act 3)")
    mount_fay_act_3 = region("Mount Fay (Act 3)")
    moss_grotto_act_3 = region("Moss Grotto (Act 3)")
    ruined_chapel = region("Ruined Chapel")
    craw_lake_act_3 = region("Greymoor - Craw Lake (Act 3)")
    court_of_craws = region("Court of Craws")

    eva_0 = region("Meet Eva")
    eva_1 = region("Eva - 1 Crest Slot")
    eva_2 = region("Eva - 2 Crest Slot")
    eva_3 = region("Eva - 3 Crest Slot")
    eva_4 = region("Eva - 4 Crest Slot")
    eva_5 = region("Eva - 5 Crest Slot")
    eva_6 = region("Eva - 6 Crest Slot")
    eva_7 = region("Eva - 7 Crest Slot")
    eva_8 = region("Eva - 8 Crest Slot")
    eva_9 = region("Eva - 9 Crest Slot")
    eva_10 = region("Eva - 10 Crest Slot")
    eva_11 = region("Eva - 11 Crest Slot")
    eva_12 = region("Eva - 12 Crest Slot")
    eva_13 = region("Eva - 13 Crest Slot")
    eva_14 = region("Eva - 14 Crest Slot")
    eva_15 = region("Eva - 15 Crest Slot")
    eva_16 = region("Eva - 16 Crest Slot")
    eva_17 = region("Eva - 17 Crest Slot")
    eva_18 = region("Eva - 18 Crest Slot")
    eva_19 = region("Eva - 19 Crest Slot")
    eva_20 = region("Eva - 20 Crest Slot")
    eva_21 = region("Eva - 21 Crest Slot")
    eva_22 = region("Eva - 22 Crest Slot")
    eva_23 = region("Eva - 23 Crest Slot")
    eva_24 = region("Eva - 24 Crest Slot")
    eva_25 = region("Eva - 25 Crest Slot")
    eva_26 = region("Eva - 26 Crest Slot")
    eva_27 = region("Eva - 27 Crest Slot")
    eva_28 = region("Eva - 28 Crest Slot")
    eva_29 = region("Eva - 29 Crest Slot")
    eva_30 = region("Eva - 30 Crest Slot")
    eva_31 = region("Eva - 31 Crest Slot")
    eva_32 = region("Eva - 32 Crest Slot")
    eva_33 = region("Eva - 33 Crest Slot")
    eva_34 = region("Eva - 34 Crest Slot")
    eva_35 = region("Eva - 35 Crest Slot")
    eva_36 = region("Eva - 36 Crest Slot")
    eva_37 = region("Eva - 37 Crest Slot")
    eva_38 = region("Eva - 38 Crest Slot")
    eva_39 = region("Eva - 39 Crest Slot")
    eva_40 = region("Eva - 40 Crest Slot")

    moss_mother_arena = arena_region(Boss.moss_mother)
    moss_mother_defeated = defeated_region(Boss.moss_mother)
    double_moss_mother_arena = arena_region(Boss.double_moss_mother)
    double_moss_mother_defeated = defeated_region(Boss.double_moss_mother)
    bell_beast_arena = arena_region(Boss.bell_beast)
    bell_beast_defeated = defeated_region(Boss.bell_beast)
    lace_arena = arena_region(Boss.lace)
    lace_defeated = defeated_region(Boss.lace)
    fourth_chorus_arena = arena_region(Boss.fourth_chorus)
    fourth_chorus_defeated = defeated_region(Boss.fourth_chorus)
    moorwing_arena = arena_region(Boss.moorwing)
    moorwing_defeated = defeated_region(Boss.moorwing)
    sister_splinter_arena = arena_region(Boss.sister_splinter)
    sister_splinter_defeated = defeated_region(Boss.sister_splinter)
    widow_arena = arena_region(Boss.widow)
    widow_defeated = defeated_region(Boss.widow)
    great_conchflies_arena = arena_region(Boss.great_conchflies)
    great_conchflies_defeated = defeated_region(Boss.great_conchflies)
    last_judge_arena = arena_region(Boss.last_judge)
    last_judge_defeated = defeated_region(Boss.last_judge)
    cogwork_dancers_arena = arena_region(Boss.cogwork_dancers)
    cogwork_dancers_defeated = defeated_region(Boss.cogwork_dancers)
    trobbio_arena = arena_region(Boss.trobbio)
    trobbio_defeated = defeated_region(Boss.trobbio)
    tormented_trobbio_arena = arena_region(Boss.tormented_trobbio)
    tormented_trobbio_defeated = defeated_region(Boss.tormented_trobbio)
    groal_the_great_arena = arena_region(Boss.groal_the_great)
    groal_the_great_defeated = defeated_region(Boss.groal_the_great)
    the_unraveled_arena = arena_region(Boss.the_unraveled)
    the_unraveled_defeated = defeated_region(Boss.the_unraveled)
    disgraced_chef_lugoli_arena = arena_region(Boss.disgraced_chef_lugoli)
    disgraced_chef_lugoli_defeated = defeated_region(Boss.disgraced_chef_lugoli)
    craggler_arena = arena_region(Boss.craggler)
    craggler_defeated = defeated_region(Boss.craggler)
    father_of_the_flame_arena = arena_region(Boss.father_of_the_flame)
    father_of_the_flame_defeated = defeated_region(Boss.father_of_the_flame)
    voltvyrm_arena = arena_region(Boss.voltvyrm)
    voltvyrm_defeated = defeated_region(Boss.voltvyrm)
    second_sentinel_arena = arena_region(Boss.second_sentinel)
    second_sentinel_defeated = defeated_region(Boss.second_sentinel)
    broodmother_arena = arena_region(Boss.broodmother)
    broodmother_defeated = defeated_region(Boss.broodmother)
    plasmified_zango_arena = arena_region(Boss.plasmified_zango)
    plasmified_zango_defeated = defeated_region(Boss.plasmified_zango)
    shrine_guardian_seth_arena = arena_region(Boss.shrine_guardian_seth)
    shrine_guardian_seth_defeated = defeated_region(Boss.shrine_guardian_seth)
    palestag_arena = arena_region(Boss.palestag)
    palestag_defeated = defeated_region(Boss.palestag)
    lost_garmond_arena = arena_region(Boss.lost_garmond)
    lost_garmond_defeated = defeated_region(Boss.lost_garmond)
    pinstress_arena = arena_region(Boss.pinstress)
    pinstress_defeated = defeated_region(Boss.pinstress)
    gurr_the_outcast_arena = arena_region(Boss.gurr_the_outcast)
    gurr_the_outcast_defeated = defeated_region(Boss.gurr_the_outcast)
    watcher_at_the_edge_arena = arena_region(Boss.watcher_at_the_edge)
    watcher_at_the_edge_defeated = defeated_region(Boss.watcher_at_the_edge)
    crawfather_arena = arena_region(Boss.crawfather)
    crawfather_defeated = defeated_region(Boss.crawfather)
    # summoned_savior_arena = arena_region(Boss.# summoned_savior)
    # summoned_savior_defeated = defeated_region(Boss.# summoned_savior)
    shakra_arena = arena_region(Boss.shakra)
    shakra_defeated = defeated_region(Boss.shakra)
    garmond_and_zaza_arena = arena_region(Boss.garmond_and_zaza)
    garmond_and_zaza_defeated = defeated_region(Boss.garmond_and_zaza)

    savage_beastfly_beast_arena = arena_region(Boss.savage_beastfly_beast)
    savage_beastfly_beast_defeated = defeated_region(Boss.savage_beastfly_beast)
    savage_beastfly_wish_arena = arena_region(Boss.savage_beastfly_wish)
    savage_beastfly_wish_defeated = defeated_region(Boss.savage_beastfly_wish)

    skull_tyrant_wish_arena = arena_region(Boss.skull_tyrant_wish)
    skull_tyrant_wish_defeated = defeated_region(Boss.skull_tyrant_wish)
    skull_tyrant_bone_bottom_arena = arena_region(Boss.skull_tyrant_bone_bottom)
    skull_tyrant_bone_bottom_defeated = defeated_region(Boss.skull_tyrant_bone_bottom)

    phantom_arena = arena_region(Boss.phantom)
    phantom_defeated = defeated_region(Boss.phantom)

    raging_conchfly_arena = arena_region(Boss.raging_conchfly)
    raging_conchfly_defeated = defeated_region(Boss.raging_conchfly)
    first_sinner_arena = arena_region(Boss.first_sinner)
    first_sinner_defeated = defeated_region(Boss.first_sinner)
    lace_cradle_arena = arena_region(Boss.lace_cradle)
    lace_cradle_defeated = defeated_region(Boss.lace_cradle)
    grand_mother_silk_arena = arena_region(Boss.grand_mother_silk)
    grand_mother_silk_defeated = defeated_region(Boss.grand_mother_silk)

    bell_eater_arena = arena_region(Boss.bell_eater)
    bell_eater_defeated = defeated_region(Boss.bell_eater)
    black_thread_moss_mother_arena = arena_region(Boss.black_thread_moss_mother)
    black_thread_moss_mother_defeated = defeated_region(Boss.black_thread_moss_mother)
    crust_king_khann_arena = arena_region(Boss.crust_king_khann)
    crust_king_khann_defeated = defeated_region(Boss.crust_king_khann)
    nyleth_arena = arena_region(Boss.nyleth)
    nyleth_defeated = defeated_region(Boss.nyleth)
    skarrsinger_karmelita_arena = arena_region(Boss.skarrsinger_karmelita)
    skarrsinger_karmelita_defeated = defeated_region(Boss.skarrsinger_karmelita)
    clover_dancers_arena = arena_region(Boss.clover_dancers)
    clover_dancers_defeated = defeated_region(Boss.clover_dancers)
    lost_lace_arena = arena_region(Boss.lost_lace)
    lost_lace_defeated = defeated_region(Boss.lost_lace)